### PR TITLE
theme-cosmo improvements

### PR DESCRIPTION
**Pull request by Kalagon**
- changed spacing (dropdown/progressbar)
- improved readability
- increased pointyness (removed rounded corners)

### CODE REVIEW

**Comment by Hellowlol** [comment]
I'd prefer if the boostrap files was left alone and you just edited the style.css. It would be much easier to revert/change etc. is that possible ore was there a lot of changes? I can't see any edits then the edit comment. (On my phone)

**Comment by Kalagon** [comment]
Hmm, I could just overwrite the bootstrap values in the style.css. I'll play around with this tomorrow, it's not much work as I didn't change too many things.

**Comment by Hellowlol** [comment]
@Kalagon I have added the rest of the themes, but I'm sure there are many bugs. If you wanna contribute id love to have some help regarding the themes

**Comment by Kalagon** [comment]
I've already seen it. Will do as I have time since I'm studying for exams
right now. Cosmo is almost done except for the progress bars. I can't seem
to get rid of the blue background that's in there by default. The only way
I got rid of it is to empty it in the bootstrap file directly. If you've
got a hint for me how to do it in the style.css I'd appreciate that ;D I
already tried overwriting it with default or inherit.

**Comment by Hellowlol** [comment]
Tried adding !important to the css?

**Comment by Kalagon** [comment]
Huh, no. Thanks, I'll try that.

**Pull request closed without merging**
