### PR TITLE
PlexPy UI Updates

### PR DESCRIPTION
**Pull request by strikerjjb**
New Editions
----------------
Added two tab UI to display some information returned from the following endpoints:
get_activity
get_history
get_home_stats

Dependencies
-------------------
Created one new library dependency on datatables.js add the download files and the cdn code to base.html
Also used the code in the plex module for grabbing thumbnails so plex module must be setup in order for plexpy module to pull image properly.

### CODE REVIEW

**Comment by Hellowlol** [comment]
Thanks for the pr. I'm busy for a couple of days but I'm really looking forward to review this pr. I also need plexpy backend code.

**Comment by strikerjjb** [comment]
@Hellowlol I am not a huge python programmer, but I could look at how some of the endpoints are set up on the other modules and port them over for the three that I am using above plus potentially one for the image pull. I think the way you set it up now it just does a pass through to plexpy which is how I coded the jquery calls to work.

**Comment by Hellowlol** [comment]
Plexpy module dynamically creates a endpoint for each API commend. I'm gonna restrict it to the ones we need.

**Comment by Hellowlol** [comment]
I just tested it now. Very nice job mate. Any chance you can add some more charts etc.

**Comment by strikerjjb** [comment]
I will look at the other endpoints and see what I can pull.  Probably will require the addition of a charting library but shouldn't be that bad.  After this was looking at updating the front end to a newer bootstrap framework possibly. [2.3.2 is kinda old]

**Comment by Hellowlol** [comment]
Go for it. Dunno how it will playout with out themes tho. Im really grateful anytime someone want contribute with anything specially the front end. In all fairness htpc manager should be rewritten from scratch with a asynchronous framework.

**Comment by strikerjjb** [comment]
I thought about angular or react on top then thought about the level of effort :).  Will see what I have time for.  Also, I found a set of BS3 plugin themes here:  https://bootswatch.com/  that could replace what we have now as it seems raysguys is not active on github much anymore.

**Comment by Hellowlol** [comment]
Let me know when you are done with this.

**Comment by strikerjjb** [comment]
@Hellowlol you want the charts in before we call this done correct?  I started on them early this week.

**Comment by Hellowlol** [comment]
No its not needed. If you happy with the pr as it is ill take it from there.

**Comment by strikerjjb** [comment]
Let's take it from where it is.  Would love for a larger audience to test and see what feedback comes in.  If there is demand for charts I can add in charts. I suspect folks are probably going to want a dashboard widget but will see.

**Comment by Hellowlol** [comment]
Alright. Ill merge with the targeted branch. People can switch to this branch for now. More work on it before i merge it with master2

**Pull request merged**
