### PR TITLE
nav-bar fixes and tweaks

### PR DESCRIPTION
**Pull request by raysguy**
Also added two app-specific config files to .gitignore.

### CODE REVIEW

**Comment by raysguy** [comment]
Well this was supposed to be better but still seeing multiple merges that I'm not seeing at my end.  Should just be the changes from a couple of hours ago to gitignore, base.html and base.css. :S

**Comment by Hellowlol** [comment]
Haha, what branch did you branch off?

**Comment by raysguy** [comment]
Recreated my master and develop branches from your master2 a couple of days ago so not sure what went wrong.  It created local hotfix branch from my master and then merged it back in.  Trying to follow "best practices" with structure and branching but it's gone a bit pear-shaped!

Usually use Github Mac app but it's a bit basic and thought Tower looked useful.  Might be a little complexed for me though!  Do all my editing in Coda - recently bought it after trying TextWrangler and Bbedit plus others.

**Comment by Hellowlol** [comment]
Ok, well you sent the pr from rg-master and its ahead of master2

The easiest solution is:

git chekcout -b somecssfix master2
Do the changes that you want to do. 
Commit
Send pr
Then merge somecssfix in rg-master

**Comment by madclicker** [comment]
Checkout

**Comment by raysguy** [comment]
Clean request sent! #160

**Pull request closed without merging**
