### PR TITLE
Fixes and tweaks for navbar

### PR DESCRIPTION
**Pull request by raysguy**
Added a couple of app-specific config files to .gitignore too.

### CODE REVIEW

**Comment by Hellowlol** [comment]
Why does in include merges from different branches back and forth? :P

**Comment by raysguy** [comment]
Well, this new Tower software uses gitflow and I’ve been trying that.  Seems that when it closes off the “hotfix” it first merges into master and then from master to develop.  Not sure why.  In future I’ll just send pull requests from master where possible.  

Honestly gotten myself so confused looking at merge histories and trying to straighten it out.  Tried rebasing from your master2 branch but now getting errors trying to sync! FML.  Going to close request, delete my develop branch and resend PR from master. /facepalm

**Comment by Hellowlol** [comment]
That has happend to me too when i tried some gui to git. Now i only use sublime github for windows and hub.

When i contributed to upstream i always branched off the default branch (master2 in this case) and dealt with all the merge conflicts in my own branch "master" branch. I have no idea if thats the best solution but that worked for me.

So if there are any git ninjas feel free to pitch in.

**Comment by madclicker** [comment]
Command line.

**Comment by Hellowlol** [comment]
Not everybody is a cli ninja @madclicker :D

**Comment by madclicker** [comment]
You asked and I tell you: cli and stackexchange.

**Pull request closed without merging**
