### PR TITLE
rg-speed

### PR DESCRIPTION
**Pull request by raysguy**
Branch up to date with your master2 branch as at end of day on 18 April 2015.

This PR updates HTPC to use minified CDN sources wherever possible, but
as agreed it retains local files and the references in base.html and
loginform.html are commented out so that local sources can easily be
enabled if desired.

To further improve speed I’ve utilised the minified CDN sources even
where the minified version isn’t used locally.

As part of the process it was necessary to update the following three
js libs:
jquery.pnotify 1.2.2 —> 1.3.1
jquery.form 3.08 —> 3.09
query.cookie unknown version —> 1.4.1

### CODE REVIEW

**Comment by Hellowlol** [comment]
Has this you verified that everything works after the libs update?
Can you make the local files default and add a option to use cnd?

**Comment by raysguy** [comment]
Fixed an issue with pnotify and made local files the default.

Would there be a way of having a CDN checkbox option in the general settings page that would automatically toggle between local and CDN?

**Comment by Hellowlol** [comment]
Yes
````
% if s.get('app_use_cnd'):
    link to cnd
%else:
   local files
%endif
   
````

**Comment by raysguy** [comment]
Thanks for the info.  I've spent hours trying to get it to work and can get the option added to the settings page without issues, but as soon as I make the changes to base.html or loginform.html HTPC no longer works and every page I try to visit gives a 500 error.  I've checked and double checked but can't get it to work.

Here are links to the three files I edited.  Please could you take a look if you get a chance and see if you can pot where I'm going wrong as it's driving me crazy trying to figure it out and I probably missed something simple! Thanks!

http://pastebin.com/daTQNmKM - settings.html
http://pastebin.com/Nm4qfjhY - base.html
http://pastebin.com/bUv19kxr - loginform.html

**Comment by Hellowlol** [comment]
You have forgot the : after else

**Comment by raysguy** [comment]
Thanks for that.  Can't believe I missed something so simple!  Sometimes when you've spent so long looking at it you can't see the wood for the trees! :)

That all seems to be working fine now though and is completed.

**Comment by Hellowlol** [comment]
It happens, I have done the same thing. Been debugging something  something and it was the wrong htpc manager...

So I know I'm nagging but could you do so library's that isn't in the cdn is is outside the endif. Example default js etc

**Comment by raysguy** [comment]
Probably doesn't help that I do a lot of it during the night with being an insomniac! :)

That's no problem, I was going to do it like that originally but wasn't sure if changing the order they're loaded would mess anything up.  Pushed the change.

**Comment by Hellowlol** [comment]
It does, but it looks good :)

**Comment by raysguy** [comment]
Ah awesome, hopefully it'll be a useful option for people :)

**Comment by Hellowlol** [comment]
@raysguy is merged, just a tip you dont need keep merging master2 into your pr is behind, ill handle that when i merge, or ill ask you to rebase your pr.:)

**Pull request merged**
