### PR TITLE
Possible fix for Visual bugs #155

### PR DESCRIPTION
**Pull request by rkorn86**

### CODE REVIEW

**Comment by thatbritguy** [comment]
This was already fixed in 67d53fe38f444b2d5deb1e98a4fb02b6b9e70f17 :)

**Comment by rkorn86** [comment]
No, it was not: See the screenshot taken with https://github.com/Hellowlol/HTPC-Manager/commit/d660d2cbde60d36a1200d50b61c592179f303ff4
Custom Module

**Comment by thatbritguy** [comment]
Ah gotcha, I had multiple custom urls when I fixed it and hadn't realised it only kicked in when the item was a dropdown.  Good spot! :)

Just tested out your PR and I think only the change to line 56 is needed - line 51 covers when it appears as a dropdown which is what I fixed.

**Comment by Hellowlol** [comment]
Thanks!

**Pull request merged**
