### PR TITLE
CP no wanted movies fix

### PR DESCRIPTION
**Pull request by fma965**
Fixes the issue with couchpotato now showing "no wanted movies" when no wanted movies... can't test plex and headphones so haven't done them.
#253

### CODE REVIEW

**Comment by Hellowlol** [comment]
I would have just changed the current text (couldn't contact cp or what evs) and checked length of movies. So we handle both a connectiom error and no wanted movies.

**Comment by fma965** [comment]
K, that seems like a bad idea to just give a generic error for anything but again it's up to you.

This is just a simple fix to fix the issue which should have never existed in the first place.

**Comment by fma965** [comment]
this isn't working any more.... @Hellowlol not sure why...

**Comment by Hellowlol** [comment]
I havnt changed anything related to it. What is the response if you call http://ip:/port/couchpotato/GetMovieList/active/5 from you browser?

**Comment by fma965** [comment]
null

**Comment by fma965** [comment]
hmm it seems that my couchpotato has broke, it won't log in :/

**Pull request merged**
