### PR TITLE
Initial startup to customise htpc

### PR DESCRIPTION
**Pull request by kooimens**

### CODE REVIEW

**Comment by kooimens** [comment]
Hmm, I as was testing some stuff in the same branche it looks like all those commits are pushed directly to this PR. Don't know if this is a problem. Let me know if I have to fix this.

**Comment by Hellowlol** [comment]
Well what is it that you want to merge here?

**Comment by kooimens** [comment]
Only the first two commits

**Comment by Hellowlol** [comment]
While im not sure i want to add a new tab to the settings page, im sure i can add something like this. Kinda busy with mylar atm, but ill get it done later

**Comment by kooimens** [comment]
Ok thanks

**Comment by kooimens** [comment]
@Hellowlol Since we have more options now, like menu order and edit dash I was thinking to extend this a bit more. I would like to be able to edit the dash/change menu order only once and then make those links invisible for everyone because it's becoming too busy. The following options seems reasonable:
1. Customize title
2. Disable github link
3. Disable edit dash
4. Disable menu order
5. Disable check for updates.

Please me know if you want a new settings tab for it or not. Then I can make a PR for it that's easy to merge for you.

**Comment by Hellowlol** [comment]
1. Ok
2. Ok
3. Ok
4. Not ok, id like this to be handled by the new access rights

Start the keyword with app_customize 
Just add a tab named customize.

**Comment by kooimens** [comment]
And for number 5? I do need fully agree about the option should be handled with access rights. I mean, I will be my dash once and will probably leave it like that in future. In that case those links are superfluous (the links, not the option to change the dash;). I don't want to see them at all, nor for my users nor for myself. And in the end it won't trouble anything to have it both customisable and regulated by access rights right?

**Comment by Hellowlol** [comment]
I updated my answer for 5. 
Just to be clear whe. You say disable do you mean no showing the links in the html or disabled like they can manually type the url to active that settings?

**Comment by kooimens** [comment]
I mean not showing the links in html. But I now realise that should not be enough?

**Comment by Hellowlol** [comment]
Well they only way to be sure if this is handled by auth control, else they can still manually paste the url and do stuff :P

**Pull request closed without merging**
