### PR TITLE
sable theme - redone

### PR DESCRIPTION
**Pull request by bakman2**
I have recreated the sable theme, not braking anything as earlier, left the colors on the buttons. 
Settings is a little more compact. 
I did remove the hardcoded inline style in dash.js to be able to style the refresh buttons in dashboard.

Other themes still look good and work, that particular icon could be a little smaller though.

### CODE REVIEW

**Comment by thatbritguy** [comment]
@Hellowlol Please revert the change to the dash.js as it messes up the style I had for the refresh buttons on all the other themes and I don't want to have to start re-editing 44 sets of theme files to try to fix this.  The class for the refresh buttons is already there in the theme.  All you need to do to change the size is to edit the theme class `.refresh-btns .btn` and add `font-size: [x]em;` to it.

Also would you mind editing the headers on the theme files to make it clear that sable is an external theme that is based on re-bootstrap but isn't a part of them.

**Comment by bakman2** [comment]
I have tried a couple of themes and the refresh looked good, but ok.

Can only overrule with !important.
I have changed the header and restored the inline style in dash.js

**Comment by thatbritguy** [comment]
Yeah it makes the buttons too large on my themes without the original inline style. In my test I didn't need !important to override though so see how you get one with that.  Thanks for changing it so quick, I appreciate it.  Would have been a major pain having to re-edit all those theme files for one button!

**Comment by bakman2** [comment]
Yeah I understand, my bad, was a bit enthousiastic. 
CSS only would be best :)

**Comment by thatbritguy** [comment]
Yeah there are various quirks in code from before Hellowlol created his awesome fork.  Generally I change the things I can as i spot them, usually whilst i'm doing something else!

**Comment by Hellowlol** [comment]
To be fair, many of the quircks are mine :p

**Pull request merged**
