### PR TITLE
Start & Quit Kodi

### PR DESCRIPTION
**Pull request by wmariz**
Add the ability to start and quit kodi.

To start kodi, it sends a udp packet to XBMC Starter
(http://yatse.leetzone.org/redmine/projects/androidwidget/wiki/XbmcStarter)

Add starterport column to kodi_servers table.

Fixed a bug where kodi servers saved settings dialog do not show.

### CODE REVIEW

**Comment by wmariz** [comment]
I'll try to fix that! Tks

**Comment by Hellowlol** [comment]
I noticed your adding everything in one branch and one pr. Only add one feature pr pull request please.

**Comment by Hellowlol** [comment]
I really appreciate people stepping up so thanks again.

**Comment by wmariz** [comment]
I thought that will be possible to create different poll request from sets of commits, but  Git just add every commit that I've made.

I will try to separate then on different branchs.

About the libs, pySMART depends on smatmontools (compiled), should I add the library anyway?

Should I put it on /libs or try to install with setuptools?

**Pull request closed without merging**
