### PR TITLE
Fix Nax

### PR DESCRIPTION
**Pull request by fma965**
Thanks to @bakman2 #302 #303

### CODE REVIEW

**Comment by fma965** [comment]
Note it will need the CSS added, i ain't doing that though.

**Comment by Hellowlol** [comment]
And this is really tested?

**Comment by fma965** [comment]
Yeah it works fine for me on sonarr and couchpotato and deluge, doesn't highlight on iframe pages but thats not a problem imo.

**Comment by fma965** [comment]
image
image
on sable theme.... CSS needs to be added for other themes but if the CSS doesn't exist no issue just no colour

**Comment by bakman2** [comment]
As it was rolled back already, maybe fix the other stuff in #303 first as well before merging

**Comment by fma965** [comment]
it wasn't rolled back though, the active class code was just commented. the theme still exists in master. so i think we should get this working ASAP then you can fix your theme. But Hellowlol can decide, till then i'm using my own fork anyway :)

**Comment by Hellowlol** [comment]
So just so i get this right: You pr will work on sabre theme, but the rest needs css? So it shouldnt be a issue then :P

**Comment by fma965** [comment]
yup thats correct, but no issue if it doesn't work on a theme it just wont add the CSS highlight :)

EDIT: @bakman2 's pr also needed the CSS added to the themes so it's no different but this PR actually works :)

**Pull request merged**
