### PR TITLE
Upgraded references to CDNs for speed. Removed redundant local files.

### PR DESCRIPTION
**Pull request by raysguy**
Trying to clean up clutter and improve responsiveness before I get around to trying to get everything upgraded to Bootstrap 3.  By replacing as many CSS and JS references in base.html as I can with CDN services to the same version it should really speed up the experience.  I was then able to delete all the js and css files I'd rendered redundant. Hope you think this is worth merging.  Used the plexsucks branch to clone so i could test with latest fixes.  Just trying to give something back given how hard you work on the project.  Tested it as much as I can and shouldn't be any issues.  I'm also currently working on a set of modern, fresh and streamlined themes which are more responsive/immersive.  Looking forward to having those ready.

### CODE REVIEW

**Comment by Hellowlol** [comment]
I want to applaud the effort you have put in regarding this, but i doubt ill change to a cnd solution as sometimes special hacks are needed and i generally dont see a speed increase (as is mostly use this at home and fetching for my own network is faster then the interwebz)

I would love to see a update to boostrap 3, just a fair warning its gonna be LOADS of work. You will have to change alot of html and js to get this working. There is a reason for why i havnt done this already... :P, honestly i dont think i ever would. 

A boostrap 3 pr would be most welcome!

**Comment by Hellowlol** [comment]
Please dont delete this branch as it would be a great ref incase we ever go that way. Im gonna test this later.
I hope to finish the pelxsucks branch and merge it with master2 later today.

**Comment by raysguy** [comment]
No worries.  I mainly use from home now too although plan to use it more on the road and once the limited access multi-users branch is complete (which I'll be throughly testing soon) I'll be giving access to family across the country and my girlfriend across the ocean in Canada. I've noticed improvements changing programs to CDN before, especially when they're using pretty old versions.

I may have underestimated the amount of work involved in updating to Bootstrap 3 but I'm planning to study up on it first so I can go into it with a better understanding of what needs to be done.  So few of these types of program are using up to date resources.  Especially when it comes to fonts the way they handle fonts.  I think I'll prioritise my project to produce a brand new set of clean, clear, modern themes for HTPC based on the existing version of Bootstrap.  The 2.x themes for Bootstrap really don't look so good on the interface and some totally mess it up.  I just about have the first one done, figuring out what code I need to tweak where and to me it looks beautiful.  That will almost be my template for the others where I'll keep the basic structure and responsive full screen experience the same but make changes to the colour pallettes and fonts to give variety and choice for most tastes.  Really excited about how it's turning out now that I've cracked the code so to speak.

Also in the pipeline is a live clock module for the dash if you think that might be useful.  Created a homepage for my site which displays the time with the background colour changing based on the heximal code the digits of the time create.  Simple but it looks really good and just rustled it up quick to have something useful instead of my basic index.html message!  I was thinking creating a modular version of that as an option could be useful to some depending on usage scenarios.

I'll definitely leave the speed-cdn branch up.  I'll probably be merging it into my own master branch soon after we finish with plexsucks and that's merged into master.

Thanks for the great communication and engaging with the community on this.  Often reluctant to approach devs with requests but you make it easy.  The more I use HTPC the more ideas I have for it and I look forward to sharing those and helping out where I can.

**Comment by Hellowlol** [comment]
I don't see a use for a live clock module but that the good thing. I'll still merge it as every user has to enable it. Come to think about it I did plan to add a clock to the weather module if I ever get to finish it.

I added all the themes I could find just incase they got deleted. I'm sure the could all need some work. I hope you plan on sending a pr for the themes.

**Comment by raysguy** [comment]
I didn't have much use for one myself until I got to playing around yesterday.  You should be able to see it at http://rs.gy.  My thought was to incorporate that into a module with maybe the colour changing option and a black and white option for the less colourful people.  I'd definitely be interested in seeing how the weather module turns out.

Yeah, I did the same.  Most of the 2.x versions unfortunately look quite bad for HTPC compared to the updated 3.x versions of the themes.  My plan is to create a full suite of themes that would give current users a modern equivalent which would broadly cover their preferences - combinations of colours, font style and font weights.  Something for everyone, but all based on the same core so that you can rest assured when developing it that everyone will have the same experience regardless of theme applied - hopefully less "bugs" caused by themes.  I'll absolutely be sending a pr for the full set.

**Comment by raysguy** [comment]
Yeah commenting out is exactly what I'd originally done when going through and took them out at the end to tidy it up.  Should be able to revert that change though to show originals as comments and restore the deleted files.

**Comment by raysguy** [comment]
Btw I've setup a new branch for developing the themes.  I've stripped out all other themes and just have my initial template in there.  So feel free to check it out.  Obviously in terms of font weight and style it's tailored to my specific preferences but I plan to create some variety amongst themes to accommodate all tastes hopefully.  It's not finished yet as I have more work to do tweaking and especially deciding what to do with the colour scheme.  Once I get this one perfect the rest will be easy though.  Main changes so far are to the typeface and also having the whole screen be filled without the odd background edges etc.  I've also removed rounded corners.

**Comment by Hellowlol** [comment]
Nice! I cant pull from that branch as it had removed the old themes etc  but I'll just have to add them manually. If you plan to send a pr the easiest is just to add the theme (for me atleast lol) so it will be a one click merge, if you don't, the current method is probably the best.

Thanks for doing this, I'll be sure to check your progress :)

**Comment by raysguy** [comment]
Sorry for the late reply.  Spent the day on the road and with family.  I'll recreate those branches.  The cdn-compat will be the compromise solution you mentioned before with the original files included and their references left commented out of the file in case user wants to revert from CDN for any reason.

For rg-theme-suite I'll create a branch that still includes all the originals with mine as separate ones for now.

**Comment by raysguy** [comment]
Hey there, just to let you know I created a new branch (rg-themes) for my theme work which is the same as your master2 branch with the only addition being my first theme: rg-imperial.  It's a work in progress but at least you can have a look at the initial tweaks to interface before I get started on colouring.  Was going to send you a PR but wasn't sure which branch to direct it to.

**Comment by Hellowlol** [comment]
If you branched off master2 you should send a pr to that branch. Everything to merged to that branch sooner or later. 

Thanks for doing this.

**Comment by raysguy** [comment]
Ah cool, I’d assumed I shouldn’t send to that whilst it’s still a work in progress.

**Pull request closed without merging**
