### PR TITLE
FontAwesome 4.3.0 and UI update

### PR DESCRIPTION
**Pull request by raysguy**
This completely updates HTPC Manager from FontAwesome 3.2.1 to 4.3.0.  All references have been updated.  It's up to date with current master2 branch of your repo as of 16 April 2015.

I've also tweaked some of the icons, mainly in dropdown menus, to better utilise the updated version and to provide a more consistent look where possible.  Also fixed typos as I've come across them.

Updated jQuery.raty.js to latest version.

Created new spinner via CSS.

Created new icons for torrent/newsnab search results.  Originally tried with SVG files to create super crisp and sharp icons but had difficulty figuring out how to get them to resize correctly, mainly in the torrentsearch.js file.  Going to work on figuring that out but in the meantime I replaced the old icons with png versions of the new ones.

Deleted unused img files.  Double-checked before deletion that there are no longer any references anywhere to them.  Some I've replaced throughout with the new FontAwesome icons and others via CSS.

Tweaked dashboard carousel to improve readability and usability as most of the image was covered by navigation buttons before.

Tested as thoroughly as possible but I can't run all modules so if you come across any odd behaviour let me know.

Going to work on creating the new themes next.  This update creates a solid foundation for that and future updates.

### CODE REVIEW

**Comment by Hellowlol** [comment]
Hi! Thanks for taking the time to do this.
I have 2 small requests, can you minify the js libs that you added (like raty and awesomefont css)

I do not like the new images you added regarding torrents providers and nzbclients. The colors and logo are wrong etc.What benefit does the new images provide?

**Comment by Hellowlol** [comment]
Thanks for doing my request.

I do not like the new images you added regarding torrents providers and nzbclients. The colors and logo are wrong etc.

What benefit does the new images provide?

**Comment by raysguy** [comment]
I'm working on the images for the torrent/nzb providers right now.  Basically I've created nice crisp and sharp svg icons for them all which will scale and look sharp even at 16x16 used in the search results.  I opted for a monotone approach and to make them consistent with the rest of the icons used throughout HTPC Manager.  I tried to capture the spirit of the original logos with them.

The problem I have is how to use them in the torrentsearch.js file and get it to automatically resize to 16x16.  I can resize them with HTML/CSS and they look great but just can't figure it out for JS.  So I dropped the png files in as placeholders until I can achieve what I'm trying to with them,  At the moment I'm working on a different approach - I'm using the svg files to create a custom font on IcoMoon which should allow for them to be used in the same way as FontAwesome icons and be resized and recoloured by font settings.

**Comment by raysguy** [comment]
Reverted the icons until I can get them to a state I'm happy with, so that I can show you the end result.  I agree there's not much benefit until I can use the svg versions.

**Comment by Hellowlol** [comment]
I assume your have tried $("someimage").css("width", 16px).css("height", 16px)?

**Comment by raysguy** [comment]
I wasn’t aware of that but just tried it out and didn’t have any success unfortunately.  For some reason the torrent search function is very glitchy for me.  Half the time it doesn’t respond or only produces and NZB search.

**Comment by Hellowlol** [comment]
Remember that torrent search only work if the torrent module is open. If not it will default to nzbsearch. And inside some modules that search field will search current module (kodi comes to mind). What browser are you using? The js should work.. Dunno why it doesn't.

**Comment by Hellowlol** [comment]
@raysguy can you make a new issue regarding torrent search with what provider you have active and what search you search for?

**Comment by raysguy** [comment]
It seems to be working at the moment.  It tends to be intermittent but I'll keep my eye on it and create an issue if it starts happening again.

**Comment by Hellowlol** [comment]
Ok. So is this pr done now so i can review and merge?

**Comment by raysguy** [comment]
Yeah, absolutely it should be good to go.

**Comment by Hellowlol** [comment]
Im gonna squash your commits one to one as there are shitloads of them :P

**Comment by Hellowlol** [comment]
Any change you get the icon in the browser tab to look better? image

**Comment by Hellowlol** [comment]
closing this as its merged.

**Comment by raysguy** [comment]
Yeah sorry I did lots of commits so I could easily revert any issues I came across.  It was tricky but fun.  Probably would have taken half the time if I wasn't learning this stuff as I went along!

**Comment by raysguy** [comment]
Yeah sure, what changes would you like made to it?

**Comment by Hellowlol** [comment]
I think you did a great job, commiting often is fine, i do it myself. But if there many i usually squash or rebase them to one before sending them upstream.

Dunno it just seems to black, with the black stuff around the "tv". I did like the new ios homescreen that you made, it looks very nice.

**Comment by raysguy** [comment]
Ah cool, I’ll see what I can do.  It’s actually the same as the new home screen icon but shrunk down to favicon size.

**Comment by raysguy** [comment]
Just wondered if you had a rough ETA on this merge being completed and if there's anything I can do to help with it.  Want to be able to start from a clean master2 branch containing this PR for the themes I'm working on.  Thanks

**Comment by Hellowlol** [comment]
in about 30 min

**Comment by Hellowlol** [comment]
Shit i thought you was talking about the other pr. This one is merged. See https://github.com/Hellowlol/HTPC-Manager/commit/942b20e00eb978464a55d52fd1d3a550c44134fd

**Comment by raysguy** [comment]
Hahaha awesome, thanks. Wasn't expecting it so soon! :)

**Comment by raysguy** [comment]
Oops, sorry, my bad.  I'd spotted the old "font" directory in the CSS folder the other day and assumed you were still working through my crazy number of commits! :)  Could you delete that folder please, as it's no longer needed.

**Comment by Hellowlol** [comment]
Yeah, ill do it next time ill commit something
Btw, regarding your upgraded favicon it will look the same on chrome:

image

**Comment by raysguy** [comment]
Thanks.

You’ll just need to delete chrome’s cache data/images for the localhost and then re-open the browser.  Should grab the new favicon :)

**Comment by Hellowlol** [comment]
Rookie mistake :p

**Comment by raysguy** [comment]
I only know because when I was testing I spent quite a while thinking it wasn’t working until I figured it out!

**Pull request closed without merging**
