### PR TITLE
Minor UI consistency changes / typo fixes

### PR DESCRIPTION
**Pull request by raysguy**
Just some minor tweaks to buttons and labels plus a few small typos as I came across them.

### CODE REVIEW

**Comment by Hellowlol** [comment]
Thanks! If your gonna fix my typos can you stick to American?  I'm not used to British :P. Btw sonarr is spelled sonarr

**Comment by raysguy** [comment]
Oh, I can’t spot anything I made British - I resisted the urge to change “favourite” to “favourite” hahaha :p

Although Sonarr is lowercase in their logo, in all their documentation and github/wiki etc they spell it “Sonarr”.  Not sure why some brands decide to go with lowercase only in their logos but not elsewhere!

**Comment by Hellowlol** [comment]
You didn't this time, but you changed utilize last time :D 

I know, but since the logo and the name inside the app is written as sonarr I'm gonna stick with that.

**Comment by raysguy** [comment]
Oops, sorry about that.  I'll have to try and remember to use US spellings if I add new text! ;)

**Pull request merged**
