### PR TITLE
Small startup to make htpc manager more customisable

### PR DESCRIPTION
**Pull request by kooimens**
I like to set the application title the same as my domain name. Furthermore, I want to disable the github link for my users. 

If you like the idea I will create some more custom settings.

### CODE REVIEW

**Comment by Hellowlol** [comment]
Can you crush the commits to one?

**Comment by Hellowlol** [comment]
Btw, please dont manually fix  stuff that already fixed in the master2 branch, this leads to merge conflicts that i have to solve before i can merge it :) the less conflicts the better :D

**Comment by kooimens** [comment]
Ok, then I will bring back the number of commits next time. Thanks for the tip. Merge conflicts were already there when I wanted to merge, before I fixed anything manually. I thought, changing the line to the same one as in master2 will solve it, but no. I will leave it like it is in future. Im still a noob;)

**Comment by kooimens** [comment]
@Hellowlol I can bring it back to one commit if you want? No problem tbh.

**Comment by kooimens** [comment]
Done #84

**Comment by Hellowlol** [comment]
You didnt need to do that, but thanks anyway! :)

**Pull request closed without merging**
