### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by wmariz**

### CODE REVIEW

**Comment by Hellowlol** [comment]
Thanks for this. I assume it wont take before @kooimens and @henkjanvries start asking for personalized dashboard order etc so i gonna see if i cant find a way to do that.

**Comment by wmariz** [comment]
I think is just a matter of add in @require(member_of(htpc.role_user)) to save_menu & save_dash functions on root.py

**Comment by henkjanvries** [comment]
ha @Hellowlol i don't really mind! but it does look good @wmariz! 
i just have 1 practical question, ive made personalised adjustments to files for the auth of users. if i want this, ill probably have to that again won't i?

**Comment by Hellowlol** [comment]
Yes, you have to do it again for each update. If i where you id fork the project. ```git checkout -b modauth```. Do your changes and push them to github.

So after each upgrade you can:
```
git checkout master2
git merge modauth
```

**Comment by Hellowlol** [comment]
@wmariz I wish it was that simple.. :P the pain is the db, the rest is easy.
I find it every hard to do even trivial stuff in sqlobject (like adding columns later etc)

**Pull request merged**
