### PR TITLE
Add actions to Sonarr+Radarr, plus general enhancements

### PR DESCRIPTION
**Pull request by jeremysherriff**
* uTorrent: set file size display to [KMG]iB to match native UI
* Dash: add status message functionality for all refreshable dash widgets
* Stats page: add 'reverse proxy' page header clickable link
* TorrentSearch page: add 'reverse proxy' page header clickable link
* Sonarr/Radarr: add action buttons
* Sonarr/Radarr: add health alerts tab
* Sonarr/Radarr: add dash widget refresh
* Sonarr/Radarr: expose health alerts on dash widgets

### CODE REVIEW

**Comment by jeremysherriff** [comment]
This is ready for merge and I've been running it as stable for a couple of weeks.

**Comment by jeremysherriff** [comment]
Sonarr/Radarr dash health alerts:
image

**Comment by jeremysherriff** [comment]
Sonarr/Radarr health tab:
image

**Comment by Hellowlol** [comment]
This done?

**Comment by jeremysherriff** [comment]
Yes, thanks

**Pull request merged**
