### PR TITLE
Radarr

### PR DESCRIPTION
**Pull request by znedw**
I've implemented basic Radarr functionality (mostly by way of copy-pasting from Sonarr, the APIs are almost exactly the same, substitute tvdbid for tmdbid and showId for movieId).

Done basic testing and I'm able to search and add movies, delete movies, force a search, rescan and other commands. Banner art works too.

I've made some assumptions around which columns to show, not sure if they're 100% what people want but it's the minimal set of what I needed to see (cinema date, if it's been downloaded, monitored quality profile).

### CODE REVIEW

**Comment by Hellowlol** [comment]
Thanks for the PR! Radar has been requested many times so Im sure many users will appreciate this pr. Im a bit busy so it might take some time before this is reviewed and merged.

**Comment by znedw** [comment]
No worries, I'm running it on my media server so I can do some proper testing

**Comment by Hellowlol** [comment]
If you get time can you fix sonarr quality its buggy? As you can see my js skills are no good

**Comment by zachnedwich** [comment]
Done... I think. The Sonarr page should wait until profile() is finished and quality has a value before loading shows.

**Comment by znedw** [comment]
@Hellowlol fixed, I think. Sonarr should wait until profile() is finished before loading shows

**Pull request merged**
