### PR TITLE
adding bootstrap tablet css for ipad landscape mode

### PR DESCRIPTION
**Pull request by rkorn86**
Problem is, that bootstrap does not apply tablet mode on ipad (landscape mode). Ive added an additional media query respecting the ipad width size in landscape mode to enable tablet css.
Im not a css guru, but this fix worked on my ipad air 2.
Without this fix, the navbar has 2 rows, where the 2nd one (having the search field and menu button) hides the "breadcrumb".

### CODE REVIEW

**Comment by Hellowlol** [comment]
Can you post a screenshot of before and after your css fix on that iPad?

**Comment by rkorn86** [comment]
Before
before
After
after

**Comment by Hellowlol** [comment]
Ok can you remove 2 items from the menu? does it stops wrapping to two lines?

**Comment by rkorn86** [comment]
I have shortened the menu names and it stopped wrapping.


PS you can check yourself without having an iPad by just resizing your browsers width to 1024px.

**Comment by Hellowlol** [comment]
Yeah, while I certainly appreciate your work regarding this pr i will not merge this. The menu will continue to wrap just as before, it just depends on many items you have in the menu. The simplest solution is to shorten the menu name. 

If you look as some of the screenshots i have posted you can see there are alot of abbverations in my menu (i have a lot of stuff active in order to test them)

**Comment by rkorn86** [comment]
Yeah, you are right.

**Pull request closed without merging**
