### PR TITLE
New Kodi Recent Albums Module

### PR DESCRIPTION
**Pull request by fma965**
PR for the new design of the kodi recent albums module :) hope you like it.

image
image
image

### CODE REVIEW

**Comment by fma965** [comment]
#248

**Comment by Hellowlol** [comment]
The images looks very dragged, is there a way we can improve it?

**Comment by fma965** [comment]
it's pretty much stretched or cropped. 

Stretched 
image

Cropped
image

**Comment by fma965** [comment]
my original idea was to have the image on the left and the text on the right but i didn't realise there wasn't a "album.description" as i was hoping to put that under the name, but obviously that hasn't happened. i think it looks better stretched rather than cropped but i'm ok with both, there might be a way to make it look better but im not aware of it.

**Comment by Hellowlol** [comment]
Streched it is then!

Btw, if your just sitting on idle hands i have a request you should do. I really like your search bar on you website. Do you think you could make htpc managers search field be always visable or atleast on the the first thing in the dropdown?

**Comment by fma965** [comment]
i can have a look, unfortunately i now have something to do as my dad wants to play Wii with me haha

**Comment by Hellowlol** [comment]
Seems dad turned off the router :D

**Comment by fma965** [comment]
Haha yeah it was like midnight so that's probably why, not much i can do about that haha but it's on now, the weekeneds it will be on most of the time.

**Pull request merged**
