### PR TITLE
re-bootstrap themes

### PR DESCRIPTION
**Pull request by thatbritguy**
Adds re-bootstrap themes to HTPC Manager and brings significant UI changes and enhancements.

### CODE REVIEW

**Comment by thatbritguy** [comment]
@Hellowlol Just a suggestion, but how about deleting the previous version tags carried over from the styxit project and implement versioning starting from this merge at v1.0.0 (using semantic versioning)?  It's more user-friendly that a commit number and a bit more "polished", plus it distinguishes your fork with it's own identity as it has now really diverged from the original project.  Could replace "Current commit" with "Version" in the about page.

**Comment by Hellowlol** [comment]
Im having issues with awesome font. :(

image

**Comment by Hellowlol** [comment]
Yeah, but i dont want to mess with it as some dockers use the version number..

**Comment by thatbritguy** [comment]
This is really strange.  Font Awesome works perfectly when CDN is enabled, but not when it is off.  Doesn't make sense as the content of font-awesome.min.css is identical to the source file on the CDN.

**Comment by thatbritguy** [comment]
Never mind I figured it out - forgot the local font path is slightly different to standard. Face palm!  Just pushed a fix for it.

**Comment by Hellowlol** [comment]
Yeah, i saw that, but i had already fixed it. Thanks for the fix anyway. Your super awesome pr is now merged. Thanks alot!!

**Comment by thatbritguy** [comment]
Yay! Thanks for merging it so quickly! :)

**Comment by Hellowlol** [comment]
I have been waiting since you released the first demo. :P

**Comment by thatbritguy** [comment]
Hahaha yeah I know.  Hadn’t originally planned to create so many but I really got into the dark themes once I started on those! :)

**Pull request closed without merging**
