### PR TITLE
Add qBittorrent downloads to dash

### PR DESCRIPTION
**Pull request by wmariz**
Hellowlol,

If you think it's good, I can add the refresh button and spin icon to others dash modules.

### CODE REVIEW

**Comment by Hellowlol** [comment]
Im gonna have to check later. The entire dash sucks imo, i think the user should be able to drag and drop the modules where they want. So if your up for it, feel free to fix the dash.

**Comment by wmariz** [comment]
Gonna give a try

**Comment by Hellowlol** [comment]
Well, i like the "square"  as they are now, but i would like if the the user could drag them to what ever place they want. On drop the current positions of the modules should be saved to the db.

**Comment by Hellowlol** [comment]
But im open to suggestions, that was just what i had planned

**Pull request closed without merging**
