### PR TITLE
Iframe Fixes

### PR DESCRIPTION
**Pull request by fma965**
Here are some iframe fixes.

Removes main scrollbar on page so don't have multiple scrollbars.
Jquery code to get height of browser window minus navbar - padding then set iframe to it.
css to make iframe not have a horrible border

### CODE REVIEW

**Comment by Hellowlol** [comment]
So your happy with the current solution? Ready to go into the main branch? I'm glad you took the js/css part I'm awefull at it.

**Comment by Hellowlol** [comment]
And it looks ok on smaller devices as well?

**Comment by fma965** [comment]
Is there a way we can tell it to not iframe on a phone? would be a lot easier than trying to make the iframe work on phones which currently doens't work well

**Comment by fma965** [comment]
oh also you would need to remove that log line which says the page it goes to as i forgot to do that.

**Comment by Hellowlol** [comment]
Check width here? https://github.com/Hellowlol/HTPC-Manager/commit/9709def6998d70c319c90c847e50ef2bd52254f2#diff-17cc4b0f9a3f999e9eb1210b9e6ac74dR13

**Comment by fma965** [comment]
Yeah could do, i mean it's not too bad from a android 1080p device.
Image

**Comment by Hellowlol** [comment]
Let's leave it for now then and we will disable it if it's a issue. I'll remove the logline when I have access to a computer

**Comment by fma965** [comment]
OK i can make a commit and PR removing that line if it's easier?

I think it's fine with the iframe being like that as i don't see many people having iframes on if they use phones, tablets look ok anyway it's just really small devices.

**Comment by fma965** [comment]
ok i removed the print line.

**Comment by Hellowlol** [comment]
Merged in master2

**Pull request merged**
