### PR TITLE
SMART data on stats page.

### PR DESCRIPTION
**Pull request by wmariz**
Adds smart data to stats page using pySMART package

### CODE REVIEW

**Comment by Hellowlol** [comment]
Any change you can write a quick guide on what file to install. There was several on the home page, i installed both and now my enviroments pats are blanked out...

**Comment by wmariz** [comment]
Hellowlol,

I used the last link from this page http://www.smartmontools.org/wiki/Download#InstalltheWindowspackage (the ​Smartmontools for Windows Package by Ozy de Jong)

**Comment by Hellowlol** [comment]
I cant seem to get this to work. I can call program from cmd and powershell, and from a script, but when i try inside htpc manager i get ```Required package 'smartmontools' is not installed, or 'smartctl' component is not on the system path. Please install and try again.``` I even removed the pysmartfolder inside libs.

**Comment by wmariz** [comment]
Hellowlol,

Are you running python as a admnistrator? There is a warning about it? (line 133 from libs/pySMART/utils.py)

**Comment by Hellowlol** [comment]
Nope, I wasnt. I did changed the setting to smartctl to administrator. But I timk it got a error then.

**Comment by wmariz** [comment]
Hellowlol,

I was able to reproduce your issue.

The problem is: python must be executed as an administrator, not just smartmontool. Try to create a .bat file that run "python htpc.py", right click on it and select "run as administrator".

Alternatively you can disable windows UAC.

**Comment by Hellowlol** [comment]
Ok, there needs to be optin about enabling and disabling this as the are some catcleaves with the install. Take a look on how I did it for ohm.

**Comment by Hellowlol** [comment]
Cool, I'll test this later today.

**Comment by Hellowlol** [comment]
Seems to work fine, acouple of things i noticed, the spinner keeps showing up on each request. Do we really need to pull this every x second? There are some typoes in reqirements.txt, and you cant have smartmoontools there, that file is used by pip, and there are no smartmoontools on pypi. What about a modal with the smart report, fx if you click the pass you get full a smart report for that drive.

**Comment by wmariz** [comment]
I don´t think it need to be refreshed every x seconds because the only information that really changes is temperature.

I can put a refresh button or a auto refresh checkbox. What you think is best? There is any example of it?

I like the modal idea, gonna give a try. There is any example of it?

I will revert requirements.txt, I thought it was a generic file.

Also I would like to make ohm and smart to be independent of psutils, the way it is, if you haven't psutils it will not show the tabs, but I'm worried about merging conflicts.

Can you merge this to another branch so I can keep working on the new ideas?

**Comment by Hellowlol** [comment]
Ex
```
import pySMART
sda = pySMART.Device('/dev/sda')
sda.all_attributes()
```

Regarding you new ideas just checkout from your current branch.

```
git checkout -b mynewideas DEVELOP-SMART
```
Its is updating atm, and i dont think it should.

**Comment by Hellowlol** [comment]
Seems good, can you remove the last _ from the settings what you entered?
 
Can you add a warning if there are no active psutil, ohm, smartmoontools? right now its just empty page.

the active_table thing what is that used for?

**Comment by wmariz** [comment]
Hellowlol,

Checkboxes in which the name ends with "enable" are used to enable/disable the entire settings page, thats why I add the _, because changing this settings makes all the fields read-only. Alternatively I can change the names, for example, from stats_ohm_enable to stats_enable_ohm. What you prefer?

Yes, I will add a warning if everything was disabled.

The active_tab variable is used to enable the first availiable tab. On the original code, the disk tab is always enabled on page load. Now, if psutil is disabled, disk tab dosen't even exist.

**Comment by Hellowlol** [comment]
The in orginal code i didnt set anything active, so by enabling ohm that would be the first tab cus be open and so on (as the disklist, processes and smart should not be in the html)

id prefer stats_x_enabled (as this is used on other modules)

**Comment by wmariz** [comment]
But if you omit the active class no tab contents will be show on page load.

Also, if I keep stats_x_enabled format, the entire settings page is disabled on uncheck (try to uncheck ohm in master2 branch)

**Comment by Hellowlol** [comment]
Notice the last d. its will work. See https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/html/form.html#L30

Are you it dont work if you omit it? Take a look on all the other html templates, you can see that its not set active.

https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/js/default.js#L14

**Comment by wmariz** [comment]
Hellowlol,

I don't know if I'm doing something wrong, but removing active_tab stuff, makes no tab content to be show. Take a look with the last commit.

**Comment by Hellowlol** [comment]
I don't think you are. The others html fires off a hashchange. Just add l14 in default.js to stats.js. I think will do it, if not I have to check later, as I'm doing this from my phone atm

**Comment by Hellowlol** [comment]
Have you tested this pr on other os?

**Comment by wmariz** [comment]
No, I haven't other os to test. Just windows.

Because I had used a library, is unlikely to have problems on linux.

**Comment by Hellowlol** [comment]
Ok, i found some bugs.

You have placed the smart function inside reload and reload is inside psutil so it dosnt load unless psutil is activated.

add
```
if (importpySMART) {
        smart();
        $('#smartl').click(function (){
            smart();
        });
    }
```
to $(document).ready(function () {...

remove the stuff about smart() inside reloadtab.

When this is fixed and its tested on other os's i think its ready for a merge? Are you happy with it now, or is there anymore you want to add?

**Comment by wmariz** [comment]
I'm happy with it now. Nothing more to add.

Unfortunately I don't have a linux box to test, can somebody do it for us?

If you think it's ready, let´s merge it. :)

**Comment by Hellowlol** [comment]
I tried to test in on my rpi yesterday, dunno if it worked since it didnt load anything, but there is only a sdcard connected to that might be the reason.

I'll try again on esxi later.

**Comment by Hellowlol** [comment]
thanks alot, really awesome work!

**Comment by wmariz** [comment]
Thank you, for showing me the right way to do it!

**Pull request merged**
